# Configuración del servidor (Adaptado para Railway y redes móviles)
server.port=${PORT:8080}
server.address=0.0.0.0

# Configuración de la Base de Datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:gymdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Propiedades de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 para revisar las tablas desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console